stat = [
    {
        "Patient_ID": "P1",
        "Visit_Date": "2023-01-02",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Hypertension",
        "Allergies": "Latex",
        "Current_Medications": "None",
        "Blood_Pressure": "157/97",
        "Heart_Rate": 78,
        "Weight_kg": 81.1,
        "Height_cm": 177.4,
        "BMI": 30.5,
        "Age": 74
    },
    {
        "Patient_ID": "P2",
        "Visit_Date": "2023-01-03",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Hypertension",
        "Allergies": "Peanuts",
        "Current_Medications": "None",
        "Blood_Pressure": "155/92",
        "Heart_Rate": 90,
        "Weight_kg": 53.1,
        "Height_cm": 172.5,
        "BMI": 31.1,
        "Age": 67
    },
    {
        "Patient_ID": "P3",
        "Visit_Date": "2023-01-04",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Hypertension",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "138/89",
        "Heart_Rate": 66,
        "Weight_kg": 78.4,
        "Height_cm": 170.1,
        "BMI": 26.1,
        "Age": 52
    },
    {
        "Patient_ID": "P4",
        "Visit_Date": "2023-01-05",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Hypertension",
        "Allergies": "None",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "132/81",
        "Heart_Rate": 77,
        "Weight_kg": 66.3,
        "Height_cm": 154.7,
        "BMI": 28.4,
        "Age": 41
    },
    {
        "Patient_ID": "P5",
        "Visit_Date": "2023-01-06",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Flu",
        "Allergies": "Peanuts",
        "Current_Medications": "None",
        "Blood_Pressure": "153/100",
        "Heart_Rate": 77,
        "Weight_kg": 70.9,
        "Height_cm": 174.2,
        "BMI": 27.4,
        "Age": 69
    },
    {
        "Patient_ID": "P6",
        "Visit_Date": "2023-01-07",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Diabetes",
        "Allergies": "Latex",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "137/88",
        "Heart_Rate": 69,
        "Weight_kg": 96.7,
        "Height_cm": 163.4,
        "BMI": 26.3,
        "Age": 57
    },
    {
        "Patient_ID": "P7",
        "Visit_Date": "2023-01-08",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Hypertension",
        "Allergies": "None",
        "Current_Medications": "None",
        "Blood_Pressure": "121/75",
        "Heart_Rate": 71,
        "Weight_kg": 93.5,
        "Height_cm": 162.8,
        "BMI": 23.7,
        "Age": 23
    },
    {
        "Patient_ID": "P8",
        "Visit_Date": "2023-01-09",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Flu",
        "Allergies": "Latex",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "122/84",
        "Heart_Rate": 67,
        "Weight_kg": 53.9,
        "Height_cm": 155.8,
        "BMI": 27.5,
        "Age": 44
    },
    {
        "Patient_ID": "P9",
        "Visit_Date": "2023-01-10",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Asthma",
        "Allergies": "None",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "142/92",
        "Heart_Rate": 91,
        "Weight_kg": 89.3,
        "Height_cm": 154.7,
        "BMI": 30.7,
        "Age": 77
    },
    {
        "Patient_ID": "P10",
        "Visit_Date": "2023-01-11",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "129/90",
        "Heart_Rate": 65,
        "Weight_kg": 56.1,
        "Height_cm": 176.0,
        "BMI": 26.2,
        "Age": 52
    },
    {
        "Patient_ID": "P11",
        "Visit_Date": "2023-01-12",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Flu",
        "Allergies": "Latex",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "124/76",
        "Heart_Rate": 75,
        "Weight_kg": 67.7,
        "Height_cm": 171.0,
        "BMI": 20.6,
        "Age": 36
    },
    {
        "Patient_ID": "P12",
        "Visit_Date": "2023-01-13",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Smith",
        "Diagnosis": "Diabetes",
        "Allergies": "Latex",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "131/88",
        "Heart_Rate": 76,
        "Weight_kg": 69.7,
        "Height_cm": 171.2,
        "BMI": 28.1,
        "Age": 59
    },
    {
        "Patient_ID": "P13",
        "Visit_Date": "2023-01-14",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Hypertension",
        "Allergies": "None",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "134/90",
        "Heart_Rate": 78,
        "Weight_kg": 88.7,
        "Height_cm": 175.0,
        "BMI": 25.1,
        "Age": 53
    },
    {
        "Patient_ID": "P14",
        "Visit_Date": "2023-01-15",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Asthma",
        "Allergies": "Peanuts",
        "Current_Medications": "None",
        "Blood_Pressure": "118/77",
        "Heart_Rate": 61,
        "Weight_kg": 71.7,
        "Height_cm": 160.4,
        "BMI": 23.7,
        "Age": 32
    },
    {
        "Patient_ID": "P15",
        "Visit_Date": "2023-01-16",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Flu",
        "Allergies": "None",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "118/74",
        "Heart_Rate": 64,
        "Weight_kg": 51.6,
        "Height_cm": 171.9,
        "BMI": 22.8,
        "Age": 37
    },
    {
        "Patient_ID": "P16",
        "Visit_Date": "2023-01-17",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Flu",
        "Allergies": "None",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "142/92",
        "Heart_Rate": 76,
        "Weight_kg": 99.8,
        "Height_cm": 172.8,
        "BMI": 32.4,
        "Age": 68
    },
    {
        "Patient_ID": "P17",
        "Visit_Date": "2023-01-18",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Diabetes",
        "Allergies": "Pollen",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "117/74",
        "Heart_Rate": 75,
        "Weight_kg": 56.4,
        "Height_cm": 168.4,
        "BMI": 22.7,
        "Age": 20
    },
    {
        "Patient_ID": "P18",
        "Visit_Date": "2023-01-19",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Asthma",
        "Allergies": "Dust",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "140/87",
        "Heart_Rate": 83,
        "Weight_kg": 78.4,
        "Height_cm": 164.3,
        "BMI": 26.3,
        "Age": 54
    },
    {
        "Patient_ID": "P19",
        "Visit_Date": "2023-01-20",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Flu",
        "Allergies": "Peanuts",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "131/85",
        "Heart_Rate": 68,
        "Weight_kg": 71.2,
        "Height_cm": 160.1,
        "BMI": 26.5,
        "Age": 47
    },
    {
        "Patient_ID": "P20",
        "Visit_Date": "2023-01-21",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Smith",
        "Diagnosis": "Hypertension",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "146/98",
        "Heart_Rate": 82,
        "Weight_kg": 85.0,
        "Height_cm": 160.8,
        "BMI": 27.3,
        "Age": 71
    },
    {
        "Patient_ID": "P21",
        "Visit_Date": "2023-01-22",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Flu",
        "Allergies": "Latex",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "126/70",
        "Heart_Rate": 65,
        "Weight_kg": 83.9,
        "Height_cm": 173.1,
        "BMI": 19.6,
        "Age": 29
    },
    {
        "Patient_ID": "P22",
        "Visit_Date": "2023-01-23",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Asthma",
        "Allergies": "Pollen",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "149/98",
        "Heart_Rate": 93,
        "Weight_kg": 52.3,
        "Height_cm": 167.6,
        "BMI": 34.7,
        "Age": 78
    },
    {
        "Patient_ID": "P23",
        "Visit_Date": "2023-01-24",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Routine Checkup",
        "Allergies": "Peanuts",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "141/90",
        "Heart_Rate": 88,
        "Weight_kg": 89.4,
        "Height_cm": 156.1,
        "BMI": 35.0,
        "Age": 62
    },
    {
        "Patient_ID": "P24",
        "Visit_Date": "2023-01-25",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Smith",
        "Diagnosis": "Hypertension",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "125/78",
        "Heart_Rate": 77,
        "Weight_kg": 83.6,
        "Height_cm": 151.3,
        "BMI": 24.1,
        "Age": 37
    },
    {
        "Patient_ID": "P25",
        "Visit_Date": "2023-01-26",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Flu",
        "Allergies": "Dust",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "112/75",
        "Heart_Rate": 61,
        "Weight_kg": 77.1,
        "Height_cm": 178.0,
        "BMI": 22.8,
        "Age": 24
    },
    {
        "Patient_ID": "P26",
        "Visit_Date": "2023-01-27",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Flu",
        "Allergies": "Dust",
        "Current_Medications": "None",
        "Blood_Pressure": "110/76",
        "Heart_Rate": 75,
        "Weight_kg": 57.0,
        "Height_cm": 172.1,
        "BMI": 22.9,
        "Age": 20
    },
    {
        "Patient_ID": "P27",
        "Visit_Date": "2023-01-28",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Dust",
        "Current_Medications": "None",
        "Blood_Pressure": "120/76",
        "Heart_Rate": 60,
        "Weight_kg": 68.3,
        "Height_cm": 183.4,
        "BMI": 23.0,
        "Age": 21
    },
    {
        "Patient_ID": "P28",
        "Visit_Date": "2023-01-29",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Routine Checkup",
        "Allergies": "Pollen",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "110/80",
        "Heart_Rate": 67,
        "Weight_kg": 86.2,
        "Height_cm": 183.0,
        "BMI": 19.7,
        "Age": 39
    },
    {
        "Patient_ID": "P29",
        "Visit_Date": "2023-01-30",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Smith",
        "Diagnosis": "Flu",
        "Allergies": "Dust",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "126/87",
        "Heart_Rate": 79,
        "Weight_kg": 76.0,
        "Height_cm": 169.2,
        "BMI": 29.0,
        "Age": 46
    },
    {
        "Patient_ID": "P30",
        "Visit_Date": "2023-01-31",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Asthma",
        "Allergies": "Pollen",
        "Current_Medications": "None",
        "Blood_Pressure": "144/90",
        "Heart_Rate": 95,
        "Weight_kg": 74.7,
        "Height_cm": 184.1,
        "BMI": 28.6,
        "Age": 63
    },
    {
        "Patient_ID": "P31",
        "Visit_Date": "2023-02-01",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Smith",
        "Diagnosis": "Flu",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "115/75",
        "Heart_Rate": 60,
        "Weight_kg": 55.6,
        "Height_cm": 168.3,
        "BMI": 19.9,
        "Age": 26
    },
    {
        "Patient_ID": "P32",
        "Visit_Date": "2023-02-02",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Pollen",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "149/93",
        "Heart_Rate": 94,
        "Weight_kg": 89.2,
        "Height_cm": 156.7,
        "BMI": 28.8,
        "Age": 66
    },
    {
        "Patient_ID": "P33",
        "Visit_Date": "2023-02-03",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Routine Checkup",
        "Allergies": "Peanuts",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "121/85",
        "Heart_Rate": 79,
        "Weight_kg": 97.6,
        "Height_cm": 165.7,
        "BMI": 28.2,
        "Age": 48
    },
    {
        "Patient_ID": "P34",
        "Visit_Date": "2023-02-04",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "None",
        "Current_Medications": "None",
        "Blood_Pressure": "129/87",
        "Heart_Rate": 71,
        "Weight_kg": 83.5,
        "Height_cm": 168.4,
        "BMI": 26.0,
        "Age": 45
    },
    {
        "Patient_ID": "P35",
        "Visit_Date": "2023-02-05",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Latex",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "144/90",
        "Heart_Rate": 75,
        "Weight_kg": 72.1,
        "Height_cm": 187.4,
        "BMI": 34.2,
        "Age": 70
    },
    {
        "Patient_ID": "P36",
        "Visit_Date": "2023-02-06",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Routine Checkup",
        "Allergies": "Pollen",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "160/95",
        "Heart_Rate": 80,
        "Weight_kg": 82.1,
        "Height_cm": 156.4,
        "BMI": 33.4,
        "Age": 75
    },
    {
        "Patient_ID": "P37",
        "Visit_Date": "2023-02-07",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Asthma",
        "Allergies": "Dust",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "125/87",
        "Heart_Rate": 82,
        "Weight_kg": 92.7,
        "Height_cm": 183.5,
        "BMI": 29.4,
        "Age": 52
    },
    {
        "Patient_ID": "P38",
        "Visit_Date": "2023-02-08",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Flu",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "125/79",
        "Heart_Rate": 73,
        "Weight_kg": 82.7,
        "Height_cm": 175.6,
        "BMI": 21.3,
        "Age": 26
    },
    {
        "Patient_ID": "P39",
        "Visit_Date": "2023-02-09",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Asthma",
        "Allergies": "Latex",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "123/87",
        "Heart_Rate": 71,
        "Weight_kg": 51.4,
        "Height_cm": 176.5,
        "BMI": 29.8,
        "Age": 42
    },
    {
        "Patient_ID": "P40",
        "Visit_Date": "2023-02-10",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Hypertension",
        "Allergies": "Latex",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "158/97",
        "Heart_Rate": 86,
        "Weight_kg": 84.6,
        "Height_cm": 185.9,
        "BMI": 34.6,
        "Age": 70
    },
    {
        "Patient_ID": "P41",
        "Visit_Date": "2023-02-11",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Hypertension",
        "Allergies": "Pollen",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "127/75",
        "Heart_Rate": 68,
        "Weight_kg": 67.6,
        "Height_cm": 183.7,
        "BMI": 22.0,
        "Age": 37
    },
    {
        "Patient_ID": "P42",
        "Visit_Date": "2023-02-12",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Flu",
        "Allergies": "Latex",
        "Current_Medications": "None",
        "Blood_Pressure": "136/85",
        "Heart_Rate": 80,
        "Weight_kg": 77.6,
        "Height_cm": 171.7,
        "BMI": 26.1,
        "Age": 44
    },
    {
        "Patient_ID": "P43",
        "Visit_Date": "2023-02-13",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Asthma",
        "Allergies": "None",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "157/96",
        "Heart_Rate": 82,
        "Weight_kg": 84.1,
        "Height_cm": 152.5,
        "BMI": 29.1,
        "Age": 73
    },
    {
        "Patient_ID": "P44",
        "Visit_Date": "2023-02-14",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Diabetes",
        "Allergies": "Dust",
        "Current_Medications": "Ibuprofen",
        "Blood_Pressure": "133/84",
        "Heart_Rate": 78,
        "Weight_kg": 85.0,
        "Height_cm": 178.9,
        "BMI": 29.2,
        "Age": 53
    },
    {
        "Patient_ID": "P45",
        "Visit_Date": "2023-02-15",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Routine Checkup",
        "Allergies": "Peanuts",
        "Current_Medications": "None",
        "Blood_Pressure": "129/80",
        "Heart_Rate": 81,
        "Weight_kg": 68.8,
        "Height_cm": 168.8,
        "BMI": 28.5,
        "Age": 45
    },
    {
        "Patient_ID": "P46",
        "Visit_Date": "2023-02-16",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Hypertension",
        "Allergies": "Latex",
        "Current_Medications": "Metformin",
        "Blood_Pressure": "146/100",
        "Heart_Rate": 90,
        "Weight_kg": 51.4,
        "Height_cm": 160.2,
        "BMI": 30.1,
        "Age": 67
    },
    {
        "Patient_ID": "P47",
        "Visit_Date": "2023-02-17",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Peanuts",
        "Current_Medications": "None",
        "Blood_Pressure": "160/95",
        "Heart_Rate": 95,
        "Weight_kg": 61.7,
        "Height_cm": 170.1,
        "BMI": 32.7,
        "Age": 74
    },
    {
        "Patient_ID": "P48",
        "Visit_Date": "2023-02-18",
        "Hospital": "Healthcare Center",
        "Doctor_Name": "Dr. Brown",
        "Diagnosis": "Hypertension",
        "Allergies": "None",
        "Current_Medications": "Albuterol",
        "Blood_Pressure": "127/82",
        "Heart_Rate": 67,
        "Weight_kg": 82.3,
        "Height_cm": 150.4,
        "BMI": 29.0,
        "Age": 48
    },
    {
        "Patient_ID": "P49",
        "Visit_Date": "2023-02-19",
        "Hospital": "City Clinic",
        "Doctor_Name": "Dr. Williams",
        "Diagnosis": "Diabetes",
        "Allergies": "Pollen",
        "Current_Medications": "Lisinopril",
        "Blood_Pressure": "112/71",
        "Heart_Rate": 79,
        "Weight_kg": 65.5,
        "Height_cm": 181.7,
        "BMI": 20.5,
        "Age": 24
    },
    {
        "Patient_ID": "P50",
        "Visit_Date": "2023-02-20",
        "Hospital": "General Hospital",
        "Doctor_Name": "Dr. Johnson",
        "Diagnosis": "Flu",
        "Allergies": "Latex",
        "Current_Medications": "None",
        "Blood_Pressure": "126/89",
        "Heart_Rate": 82,
        "Weight_kg": 50.9,
        "Height_cm": 184.8,
        "BMI": 25.4,
        "Age": 50
    }
];